# Prettier configuration
printWidth: 100
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
quoteProps: as-needed
trailingComma: es5
bracketSpacing: true
bracketSameLine: false
arrowParens: avoid

# YAML-specific settings
overrides:
  - files: "*.yml"
    options:
      tabWidth: 2
      printWidth: 120
      singleQuote: false
  - files: "*.yaml"
    options:
      tabWidth: 2
      printWidth: 120
      singleQuote: false
